config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  

  resources :users
  get 'page/index'
  

  root 'sessions#new'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    
       user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
         can :read, :all
       end
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    
    
    # See the wiki for details:
    # Definindo ability
    #   https://github.com/ryanb/cancan/wiki/Defining-Abilities
    # Checking Abilities
    #   https://github.com/ryanb/cancan/wiki/checking-abilities
    # Authorizing controller actions
    #  https://github.com/ryanb/cancan/wiki/authorizing-controller-actions
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, presence:true
  
  validates :email, presence:true,
                    uniqueness:true,
                    format: {
                        with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
                    }
                    
  def to_s
      "#{name}"
  end
      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   #Prevent CSRF attacks by raising an exception.
   #For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private
  
  def current_user
    User.where(id: session[:user_id]).first
  end
  helper_method :current_user
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in.'
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    #@user = User.find(params[:id])
    #unless @user == current_user
     # redirect_to :back, :alert => "Access denied."
    #end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      #redirect_to @user, notice: 'User was successfully created.'
      redirect_to root_url, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Benaia Motors</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" type="text/css"  href="application.scss" /> 
  </head>
  <body>
    <% if current_user %>
    <table style="width:100%">
      <tr>
        <td>
          <ul id="nav">
            <li><%= link_to "Home", page_index_path %></li>
            <li><%= link_to "Usuários", users_path %></li>
              <li>
                <% if current_user %>
                <a>Cadastros</a>
                <ul>
                  <li><a href="#">Carros</a></li>
                  <li><a href="#">Contas</a></li>
                </ul>
                <% end %>
              </li>
              <li>
                <% if current_user %>
                <%= link_to "Sair", logout_path%>
                <% end %>
              </li>
          </ul>
          </tr>
        </table>
        <% end %>
     <%= yield %>
  </body>
</html>

app/views/page/index.html.erb
<html>
  <head>
    <link rel="stylesheet" type="text/css"  href="mainMenu.css" /> 
  </head>
  <body>
</body>
</html>
        

app/views/users/_form.html.erb
  <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
  
        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= f.label :Nome %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label "E-mail" %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :Senha %><br>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label "Confirme Senha" %><br>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
  <p id="notice"><%= notice %></p>
  
  <h1>Listing Users</h1>
  
  <table>
    <head>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>
    </head>
  
    <body>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </body>
  </table>
  <br>
  
  <%= link_to 'New User', new_user_path %>
  <%= link_to 'Home', page_index_path %>

app/views/users/new.html.erb
<h1>Novo Usuário</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>
<%= link_to 'Home', page_index_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>